export const SUBJECT = {
  CODE: "CODE",
  MOVIE: "MOVIE",
  BOOK_FICTIONNAL: "FICTIONNAL_BOOK",
  GAME_BOARD: "GAME_BOARD",
  GAME_VIDEO: "GAME_VIDEO",
  TEAMS: "TEAMS",
  FUTUR: "FUTUR",
  BOOK_NON_FICTIONNAL: "BOOK_NON_FICTIONNAL",
}

export type SUBJECT = keyof typeof SUBJECT

export const CATEGORY = {
  THOUGH: "THOUGH",
  INSPIRATION: "INSPIRATION",
}

export type CATEGORY = keyof typeof CATEGORY

export const TECHNO = {
  REACT: "REACT",
  TYPESCRIPT: "TYPESCRIPT",
  SQL: "SQL",
  GRAPHQL: "GRAPHQL",
  POSTGRESQL: "POSTGRESQL",
  REDUX: "REDUX",
  NEXTJS: "NEXTJS",
  SVELTE: "SVELTE",
  SVELTEKIT: "SVELTEKIT",
  NODEJS: "NODEJS",
}

export type TECHNO = keyof typeof TECHNO
