export const SUBJECT = {
  BOOK_FICTIONNAL: "FICTIONNAL_BOOK",
  BOOK_NON_FICTIONNAL: "BOOK_NON_FICTIONNAL",
  CODE: "CODE",
  FUTUR: "FUTUR",
  GAME_BOARD: "GAME_BOARD",
  GAME_VIDEO: "GAME_VIDEO",
  MOVIE: "MOVIE",
  TEAMS: "TEAMS",
}

export type SUBJECT = keyof typeof SUBJECT

export const CATEGORY = {
  INSPIRATION: "INSPIRATION",
  THOUGH: "THOUGH",
}

export type CATEGORY = keyof typeof CATEGORY

export const TECHNO = {
  ANSIBLE: "ANSIBLE",
  AWS: "AWS",
  CSS: "CSS",
  ETL: "ETL",
  GRAPHQL: "GRAPHQL",
  HTML: "HTML",
  JAVA: "JAVA",
  JAVASCRIPT: "JAVASCRIPT",
  LINUX: "LINUX",
  NEXTJS: "NEXTJS",
  NODEJS: "NODEJS",
  POSTGRESQL: "POSTGRESQL",
  PYTHON: "PYTHON",
  REACT: "REACT",
  REDUX: "REDUX",
  SQL: "SQL",
  STORYBOOK: "STORYBOOK",
  SVELTE: "SVELTE",
  SVELTEKIT: "SVELTEKIT",
  TAILWIND: "TAILWIND",
  TERMINAL: "TERMINAL",
  TYPESCRIPT: "TYPESCRIPT",
  VERCEL: "VERCEL",
  VITE: "VITE",
  VUE: "VUE",
  WINDICSS: "WINDICSS",
}

export type TECHNO = keyof typeof TECHNO

export const SOFT_SKILLS = {
  ACCOUNTING: "ACCOUNTING",
  BUSINESS_DEVELOPMENT: "BUSINESS DEVELOPMENT",
  CHANGE_MANAGMENT: "CHANGE MANAGMENT",
  FINANCE: "FINANCE",
  MANAGEMENT: "MANAGEMENT",
  NEGOCIATION: "NEGOCIATION",
}

export type SOFT_SKILLS = keyof typeof SOFT_SKILLS
