import { Open_Sans, Roboto_Mono, Roboto_Slab } from "next/font/google"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// If loading a variable font, you don't need to specify the font weight
const roboto_slab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
  display: "swap",
})

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
})

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${roboto_slab.variable} ${open_sans.variable} ${roboto_mono.variable}`}
    >
      <body>{children}</body>
    </html>
  )
}
